version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: casino_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./casino:/var/www/html
    depends_on:
      - mysql
    ports:
      - "9000:9000"

  mysql:
    image: mysql:5.7
    container_name: casino_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: casino
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: casino_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./casino:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
