version: '3.8'

services:
  app:
    build:
      context: ./casino     # 👉 arahkan ke folder Laravel
      dockerfile: ../Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./casino:/var/www   # 👉 mount folder Laravel ke container
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casino
      MYSQL_USER: casino_user
      MYSQL_PASSWORD: casino_pass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
  
